### ISSUE TITLE
Category page gives jquery/ui warning

### ISSUE THREAD

**Issue by DerFrenk** [EmicoEcommerce/Magento2Tweakwise-archived#109]
Issue Brief
--
We've recently upgraded our Magento2 installation from 2.3.1 to 2.3.4. When I now go to a category page, the following message is visible in the devtools console:

![image](https://user-images.githubusercontent.com/6249209/75883784-d6de9880-5e23-11ea-8253-6f538de68ad8.png)

This is caused by the following line of code:
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/v2.1.8/src/view/frontend/web/js/navigation-filter.js#L8

Magento splitted jQuery UI into multiple files like jquery-ui-modules/core`, `jquery-ui-modules/widget`, etc. See https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/compat.js for the full list of modules.

When jquery/ui is requested as dependency, compat.js will now be loaded instead. This compatibility file loads all jquery-UI modules with separate requests, which hurts the performance of our category pages quite bad.

In navigation-filter.js I guess you only need the Widget module, so instead of `jquery/ui` the file `jquery-ui-modules/widget` should be listed as dependency.
Those files also contain references to jquery/ui, and should be updated:
 - https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/src/view/frontend/web/js/navigation-form.js#L8
 - https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/src/view/frontend/templates/product/layered/slider.phtml#L47
 - https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/src/view/frontend/templates/product/layered/swatch.phtml#L94

Environment
--
* Magento Version: 2.3.4
* Tweakwise Version: 2.1.7
* Magento Deploy Mode: production,development

Steps to reproduce
--
1. Install Magento 2.3.4 + Tweakwise
2. Import some products, go to a category page
3. Open your devtools Console + check the warning

Actual result
--
See ^

Expected result
--
- All jquery-ui-modules should be loaded separately instead of referencing `jquery/ui`, so there won't be a warning in the console anymore

**Comment by edwinljacobs** [comment]
Hi,

We noticed this issue as well. To reference your comment:

> Magento splitted jQuery UI into multiple files like jquery-ui-modules/core, jquery-ui-modules/widget`, etc. See https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/compat.js for the full list of modules.

do you perhaps know since when magento included the "splitted" jquery variant? The point being that we do not want to maintain multiple versions of the module (one for the splitted jQuery variant and one for the old variant). We strive to maintain compatibility with at least 2.2.10 (this is mentioned in the README.md (https://github.com/EmicoEcommerce/Magento2Tweakwise)), I cant see the ui-modules folder there :( 

Perhaps its an option to include a different js component depending on magento version. That could be a solution. So instead of js/navigation-form we would also get js/navigation-form-compat which would be referenced in data-mage-init if the magento version is lower then the first version where the splitted jQuery variant is included. A similar construction would apply to the other js components. Sadly this would lead to duplicated code but that is problably unavoidable.

If you see a different solution let us know!

**Comment by DerFrenk** [comment]
> do you perhaps know since when magento included the "splitted" jquery variant?
Yeah, it was added in 2.3.3 (https://github.com/magento/magento2/tree/2.3.3/lib/web/jquery).

I already thought that it would be hard/impossible to keep it backwards compatible. It's a bit hacky, but you could try to do it with require's `map` option. Set an option `loadjQueryUiAsModule` in the head, and use this as map config:

    "emico-jquery-ui": (window.loadjQueryUiAsModule === true ? 'jquery-ui-modules/widget' : 'js/datalayer/base')

This works only when you need 1 specific module, and it feels a bit hacky. However, this way prevents you from having duplicate code.

The other option would be what you say I guess.

**Comment by edwinljacobs** [comment]
This has been added to our backlog. In the meantime, Is it an option for you to override the js/phtml files in your project? We are currently implementing ajax filtering and a lot has changed in those js and phtml files. We will fix this issue after the ajax implementation is done.

**Comment by edwinljacobs** [comment]
I opted for a different js component based on the magento version. If the M2 version is less then 2.3.3 we include references to the full jquery/ui otherwise it will reference the needed modules. 

This fix has been included in the ajax filtering feature, I currently have no exact timetable on when that is released but it will be soon. In this feature only the slider has references to jQuery/ui. You can check branch feature/ajax-filtering if you are interested

With kind regards

**Comment by edwinljacobs** [comment]
This will be included in a release-candidate release this week. This release will also include ajax filtering as an option. Note that this release will not yet be marked as a stable release.

Ill update this again when this release is created.

**Comment by edwinljacobs** [comment]
We have added beta release v3.0.0-beta.1 where this should be fixed. There is a whole lot more going on in that release and it is as of yet marked unstable.

**Comment by edwinljacobs** [comment]
It has been a while but release https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v3.0.0 contains the fix for this issue. That being said it is major version update and it contains numerous backwards compatibility breaks, mostly on templates and javascript components.

**Comment by edwinljacobs** [comment]
Closed since the fix has been released

**Comment by edwinljacobs** [comment]
Sadly this is not fixed completely :(

```php
   <script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
```

still references jquery/ui. This was a copy paste from magento. They removed the jquery/ui reference from 2.3.3 and onwards

**Comment by edwinljacobs** [comment]
The last jquery/ui reference has been removed in https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v3.2.0

With kind regards
