### ISSUE TITLE
category in search results goes to category without search result

### ISSUE THREAD

**Issue by mediactbv** [EmicoEcommerce/Magento2Tweakwise-archived#11]
When going to the search page with a search result, it shows the search result with filters and the left side. On top are the category filters. When clicking on a category filter you are directly going to that category without the search result.

Environment
- PHP Version: 70
- Magento Version: 2.1.7
- Tweakwise Version: 1.0.1
- Tweakwise Export Version: 1.0.2
- Magento Deploy Mode: production

Steps to reproduce

1 go to a search result page with a search term, make sure there are categories available to search in. All categories at the left side for filtering have a direct url to the category page.

Actual result
--
1. All categories at the left side for filtering have a direct url to the category page.

Expected result
--
1, After clicking on a category, the current search result should filter all products based on the category

**Comment by Fgruntjes** [comment]
You could change the Layered navigation -> Category filters as link setting to "No". This will result in the expected behavior. However the same behavior will be used when using category filters on category pages.

Currently we do not have the option to choose this option depending on search result or category pages. If this is required please make a feature request with Tweakwise.
