### ISSUE TITLE
Emico_Tweakwise composer.json error: Unable to unserialize value

### ISSUE THREAD

**Issue by bmelman** [EmicoEcommerce/Magento2Tweakwise-archived#133]
the file: src/composer.json
`../composer.json`

Is generating an error 
`Emico_Tweakwise composer.json error: Unable to unserialize value. Error: Syntax error  `

whenever i try to enable/disable a module using magento module:enable

same goes for Magento2TweawiseExport

removing the files (they seem to be files, not symlinks) fix this issue

composer v 1.10.17
magento 2.4.0

**Comment by edwinljacobs** [comment]
Hi,

I noticed a similar issue somewhere on the frontend of one of our customers. I am unsure why we have those symlinks in the repo to begin with but this was not an issue previously. I found exactly what you found, that they are files instead of symlinks which explains the error. I haven't yet looked into why they are files in the first place. Most likely we will remove them but I do want to find out why this is an issue. In the meantime is it an option to use a patch to work around this issue Perhaps using cweagens or vaimo composer patches?

```
diff --git a/src/composer.json b/src/composer.json
deleted file mode 120000
index d637625..0000000
--- a/src/composer.json
+++ /dev/null
@@ -1 +0,0 @@
-../composer.json
\ No newline at end of file
```

here is a generated patch from my machine (i did not test if it works)

**Comment by bmelman** [comment]
I just threw away the composer.json files in /src, and flushed the cache

The reference path of the source file should be relative to the repository, not sure if ../composer.json works, also some OS'es (i.e. windows) seem to have issues with symlinks

**Comment by edwinljacobs** [comment]
Hi,

The module directory structure changed with https://github.com/EmicoEcommerce/Magento2Tweakwise/releases/tag/v3.2.0. This issue should be fixed with that release.

With kind regards
