### ISSUE TITLE
Every slider shows currency on dragging the slider

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2Tweakwise-archived#59]
Issue Brief
--
All sliders show currency upon sliding, even when the filter attached to it is no price filter. 

Environment
--
* PHP Version: 7.1
* Magento Version: 2.2.7
* Tweakwise Version: 1.4.4
* Tweakwise Export Version: 1.2.3
* Magento Deploy Mode: production

Steps to reproduce
--
1. Install/configure Tweakwise and export products to Tweakwise.
2. Create a filter template 
3. Add a new non-price filter  
4. Set filter to display as slider
5. Go to the front-end and see that upon sliding the slider you will see a currency even when the field does not have anything to do with prices.

Actual result
--
1. Currency is shown upon sliding
![image](https://user-images.githubusercontent.com/10864061/52952614-5f0f0e80-3385-11e9-818a-0f270a974728.png)

Expected result
--
List the expected results as a bullet list of expectations
1. Currency is not shown upon sliding

**Comment by EduardSelles** [comment]
Hi Arnoud, Thank you for bringing this problem. It's clear and we must certainly solve this. We fix this as soon as possible.

**Comment by edwinljacobs** [comment]
Hello,

We decided to make use of the prefix and postfix fields in available in the navigator, each filter associated to a filter template can have a prefix and postfix. The slider labels will be rendered as
"prefix" + {currentSliderValue} + "postfix" (note the lack of spaces). This means that no slider will display currency symbols (even price sliders) untill the prefix and postfix are configured in the navigator.

In our code we just assumed that the slider is a price slider, this assumption is not correct and therefor it should be removed. Since the prefix and postfix fields in the navigator are specifically designed to fill this role they should be used. Sadly this introduces a break for current installations (their slider does not function the same after updating). This fix is not yet released and is now up for testing. If you want to check if said fix will help your issue you can require it via composer with 

composer require emico/tweakwise "dev-issue/100674-slider-always-shows-currency-symbol-on-dragging"

After testing testing is complete we will release this fix.

With kind rergards

**Comment by arnoudhgz** [comment]
@edwinljacobs Thanks for the quick fix! I'll wait till the next release.

**Comment by edwinljacobs** [comment]
This has been released in v1.4.6
