### ISSUE TITLE
Feed property urls in layered navigation add []

### ISSUE THREAD

**Issue by maxserv-woostelbos** [EmicoEcommerce/Magento2Tweakwise-archived#81]
Issue Brief
--
The layered navigation urls adds [] to every param. For example: when you select the attribute "type" the url that is generated is: type%5B0%5D=attribute_value. 

Environment
--
* PHP Version: (7.1)
* Magento Version: 2.2.8
* Tweakwise Version:v1.4.9
* Tweakwise Export Version:v1.3.4
* Magento Deploy Mode: (production)

Steps to reproduce
--
1. Go to https://www.morres.nl/collectie/wonen/banken/
2. Select one of the options for the attibute "Maat"
3. Check the url and notice that type= looks like: ?type%5B0%5D=

Actual result
--
1. Crawlers can index on type= and type%5B0%5D=

**Comment by edwinljacobs** [comment]
Yes this is expected behavior. These query parameters are passed on to the tweakwise navigator to determine which products should be rendered. We are working on a mechanism which makes these urls "pretty" but this is still in beta.

If you do not want those urls to be crawled we suggest updating robots in magento.

With kind regards

**Comment by edwinljacobs** [comment]
The ^2.0 releases have a mechanism for pretty filter urls.

With kind regards
